---
title: "User Manual: Paired differential gene usage analysis with IgGeneUsage"
author: "SK"
date: "Oct 20, 2021"
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{User Manual: IgGeneUsage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(comment = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
```



```{r}
require(IgGeneUsage)
require(knitr)
require(ggplot2)
require(ggforce)
require(gridExtra)
require(ggrepel)
require(rstan)
require(reshape2)
rstan_options(auto_write = TRUE)
```



```{r}
data("d_zibb_pair")
data("d_zibb")
```


```{r}
# source("../R/dgu.R")
# source("../R/loo.R")
# source("../R/utils.R")
# source("../R/utils_input.R")
```





```{r}
dgu_pair <- IgGeneUsage::DGU(ud = d_zibb_pair,
                               mcmc_warmup = 1000,
                               mcmc_steps = 2500,
                               mcmc_chains = 4,
                               mcmc_cores = 4,
                               adapt_delta = 0.99)
```


```{r}
knitr::kable(dgu_pair$glm_summary, digits = 2)
```


```{r}
ggplot(data = dgu_pair$ud$proc_ud)+
  geom_sina(aes(x = gene_name, y = gene_usage_prop_1), col = "darkorange")+
  geom_sina(aes(x = gene_name, y = gene_usage_prop_2), col = "steelblue")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```



```{r}
dgu_unpair <- IgGeneUsage::DGU(ud = d_zibb,
                               mcmc_warmup = 1000,
                               mcmc_steps = 2500,
                               mcmc_chains = 4,
                               mcmc_cores = 4,
                               adapt_delta = 0.99)
```


```{r}
knitr::kable(dgu_unpair$glm_summary, digits = 2)
```


```{r}
ggplot(data = dgu_unpair$ud$proc_ud)+
  geom_sina(aes(x = gene_name, y = gene_usage_prop, col = condition))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "top")+
  scale_color_manual(values = c("darkorange", "steelblue"))
```


```{r}
ppc_rep <- dgu_unpair$ppc_data$ppc_rep

ggplot(data = ppc_rep)+
  facet_wrap(facets = ~sample_name)+
  geom_point(aes(x = ppc_mean_count, y = observed_count))+
  geom_errorbar(aes(x = ppc_mean_count, y = observed_count, 
                    ymin = ppc_L_count, ymax = ppc_H_count))+
  theme_bw()
```

```{r}
plot(dgu_unpair$glm, par = "z_mu")
plot(dgu_unpair$glm, par = "z")
```



