// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4dgu_pair_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4dgu_unpair_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gu_anova_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gu_univar_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4zibb_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4dgu_pair_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dgu_pair_mod, 0},
    {"_rcpp_module_boot_stan_fit4dgu_unpair_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4dgu_unpair_mod, 0},
    {"_rcpp_module_boot_stan_fit4gu_anova_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gu_anova_mod, 0},
    {"_rcpp_module_boot_stan_fit4gu_univar_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gu_univar_mod, 0},
    {"_rcpp_module_boot_stan_fit4zibb_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4zibb_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_IgGeneUsage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
